### ISSUE TITLE
Allakore_Remote_Issue

### ISSUE THREAD

**Issue by VinitPanchal1983** [senjaxus/AllaKore_Remote#10]
Nice Application But issue is its a very slow and File Transfer Control is good but same this issue file transfer so fast but every time i will write in save dialog box in file name and u will not use in TCPPort  use only udp port its a very fast and some time Your Application is very loaded in windwos so please check and get me solutions and now Your Application its very excellent and i will suggestion u will like modified Ammyy Admin And Check Network Algorithm and Change in Your code and client side customize build Application..
Please Read This And Immediate   Code Change......

**Comment by senjaxus** [comment]
Hello, thank you for your comment. I am working to improve the performance of the project.

I have now made considerable gains without using the UDP Protocol. I am conducting studies to see if it is possible and will be worth the implementation.


A big hug!
