### ISSUE TITLE
XE10 Seatlle

### ISSUE THREAD

**Issue by lincesmarques** [senjaxus/AllaKore_Remote#9]
Estou tentando converter para delphi xe10, mas estou tendo problemas com o servidor por conta de algumas propriedades do indy que não existem mais na nova versão do Delphi.

**Comment by saulowilson** [comment]
Mas se eu não me engano, este projeto não usa componentes Indy. Apenas o componente nativo de Sockets.

**Comment by sygecom** [comment]
Alguém tem algum problema da tela ficar cortada em algum remoto, não consigo resolver isso.

**Comment by senjaxus** [comment]
Problema corrigido!
Agora o projeto é 100% compatível com Delphi Seattle.

**Comment by sygecom** [comment]
Obrigado, irei testar

Leonardo Machado
51-3442-3975
51-99191-3474
www.sygecom.com.br

Em 4 de jun de 2017 15:24 -0300, Maickonn Richard <notifications@github.com> escreveu:
